# *************************************************************************
# **  See https://fbricon.github.io/posts/use-github-releases-as-p2-repo/
# **
# **  This file is part of the RiseClipse tool
# **
# **  Contacts:
# **      dominique.marcadet@centralesupelec.fr
# **      aurelie.dehouck-neveu@edf.fr
# **  Web site:
# **      https://riseclipse.github.io
# *************************************************************************

name: Release as Eclipse p2 update site

on: workflow_dispatch

jobs:
  build:
    # Use a specific version to avoid unattended changes with latest
    runs-on: ubuntu-24.04
    name: Make an Eclipse p2 update site

    steps:
    - name: Checkout ${{ github.event.repository.name }}
      uses: actions/checkout@v6
      with:
        path: ${{ github.event.repository.name }}

    - name: Setup Java
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: '21'
        cache: 'maven'

    - name: Build with Maven
      run: |
        cd ${{ github.event.repository.name }}
        mvn --batch-mode -Pupdate-site verify

    - name: Get version from pom.xml
      run: |
        cd ${{ github.event.repository.name }}
        VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        echo "project_version=$VERSION" >> $GITHUB_OUTPUT
      id: get_version

    - name: Upload flat p2 update site
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: |
          ${{ github.event.repository.name }}/fr.centralesupelec.edf.riseclipse.update-site/target/flat-repository/*
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: v${{ steps.get_version.outputs.project_version }}
        name: "RiseClipse P2 Update Site v${{ steps.get_version.outputs.project_version }}"

